### ISSUE TITLE
Improvement: Trigger for completer

### ISSUE THREAD

**Issue by akornilov** [eclipse/ceylon-ide-eclipse#1891]
The Idea IDE starting suggest me something when I typing text. It very helpful and save time. I don’t need write exactly “shared” and other annotations, keywords, values and etc. I just choose what required. But in Eclipse the completion tool triggered only when I have typed dot. Is it possible to change triggering logic? For example, activates completer when user typed at least 3 characters and after 200 ms delay (delay is option in settings)?

**Comment by luolong** [comment]
You can always press `Ctrl+Space` to get context sensitive completion.

**Comment by akornilov** [comment]
I know, but it's so boring and work slowly :) For example when I use the Eclipse for Java I can change the autocompletion triggering logic like this:
https://stackoverflow.com/questions/5929773/improving-eclipse-autocompletion

**Comment by gavinking** [comment]
> But in Eclipse the completion tool triggered only when I have typed dot. Is it possible to change triggering logic? 

Yes, you can change it in 'Preferences ... > Ceylon > Editor > Completion > Proposal list auto-activation'.

**Comment by akornilov** [comment]
Naturally, I have tried this option, but it doesn't work for me (like in Idea).
