### ISSUE TITLE
Roku Plugin installing in eclipse

### ISSUE THREAD

**Issue by ajaypaudel** [eclipse/ceylon-ide-eclipse#1893]
Hello,
I am trying to install Roku Plugin in eclipse but when i try it always says"cannot perform operation"  and after sometime it gives error of:
"Cannot complete the install because one or more required items could not be found.
  Software being installed: BrightScript Core 1.2.0.201610272359 (com.roku.brightscript.ide.eclipse.core.feature.group 1.2.0.201610272359)
  Missing requirement: BrightScript Core 1.2.0.201610272359 (com.roku.brightscript.ide.eclipse.core.feature.group 1.2.0.201610272359) requires 'org.eclipse.dltk.core 5.0.0' but it could not be found"
how to solve this can you guys help me out?

**Comment by luolong** [comment]
This does not sem to be Ceylon-IDE related issue?
